

ALTER PROCEDURE [dbo].[SP_INS_USUARIO]
   @PV_CODIGO VARCHAR (20),
   @PV_NOMBRES VARCHAR (100),
   @PV_APELLIDOS VARCHAR (100),
   @PV_MAIL VARCHAR (100),
   @PD_FECHA_NACIMIENTO DATETIME,
   @PV_CONTRASENA VARCHAR (100),
   @PI_USUARIO_CREACION INTEGER


AS
	DECLARE @CONTADOR_ID INTEGER;
BEGIN
   



	SELECT  @CONTADOR_ID=ISNULL(MAX(ID_USUARIO),0)+1
	FROM USUARIOS;

	INSERT INTO USUARIOS(ID_USUARIO,CODIGO,NOMBRES,APELLIDOS,MAIL,FECHA_NACIMIENTO,CONTRASENA,ESTADO,USUARIO_CREACION,FECHA_CREACION)
	VALUES(@CONTADOR_ID,@PV_CODIGO,@PV_NOMBRES,@PV_APELLIDOS,@PV_MAIL,@PD_FECHA_NACIMIENTO,@PV_CONTRASENA,'A',@PI_USUARIO_CREACION,GETDATE());


END